- id: '1599686759226'
  alias: Check Battery State
  description: ''
  trigger:
  - minutes: '/1'
    platform: time_pattern
  condition: []
  action:
  - data: {}
    entity_id: sensor.low_battery_entities
    service: homeassistant.update_entity
  mode: single