- platform: template
  sensors:
    entities_with_issues:
      friendly_name: "Entities With Issues"
      value_template: >-
        {%- set domains = ['light', 'switch', 'sensor', 'zwave', 'lock'] -%}
        {%- set count = namespace(value=0) -%}
        {%- for domain in domains -%}
        {%- for item in states[domain] if ( (not (item.entity_id in states.group.entities_exclude_from_monitoring.attributes.entity_id)) and (item.state | lower == "unavailable" or item.state| lower == "unknown" or item.state | lower == "dead") ) -%}
        {%- set count.value = count.value + 1 -%}  
        {%- endfor -%}
        {%- endfor -%}
        {{ count.value }}    
      attribute_templates:
        entities: >-
          {%- set domains = ['light', 'switch', 'sensor', 'zwave', 'lock'] -%}
          {%- set outputString = namespace(value='[') -%}
          {%- for domain in domains -%}
          {%- for item in states[domain] if ( (not (item.entity_id in states.group.entities_exclude_from_monitoring.attributes.entity_id)) and (item.state | lower == "unavailable" or item.state| lower == "unknown" or item.state | lower == "dead") ) -%}
          {%-  set outputString.value = outputString.value + '["' + item.entity_id + '",{"friendly_name": "' + item.attributes.friendly_name + '","state":"' + item.state + '"}],' -%}
          {%- endfor -%}
          {%- endfor -%}    
          {%- set outputString.value = outputString.value[:-1] -%}
          {%- set outputString.value = outputString.value + ']' -%}
          {{ outputString.value }}
