- id: '1599654319526'
  alias: Check for Entities with Issues
  description: ''
  trigger:
  - minutes: '/1'
    platform: time_pattern
  condition: []
  action:
  - data: {}
    entity_id: sensor.entities_with_issues
    service: homeassistant.update_entity
  mode: single
